FROM node:alpine

WORKDIR /usr/app
COPY ./ ./

RUN npm install

CMD [ "npm", "start" ]

# RUN DOCKER WITH PORT MAPPING FROM COMMAND LINE
# docker run -p 8080:8080 <image name>
# LEFT TO COLON IS PORT OF LOCAL MACHINE WHILE OTHER IS PORT IN CONTAINER
